[phases.setup]
aptPkgs = [
  "chromium",
  "chromium-driver",
  "fonts-liberation",
  "fonts-noto-color-emoji",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libcups2",
  "libdrm2",
  "libgbm1",
  "libgtk-3-0",
  "libnspr4",
  "libnss3",
  "libxcomposite1",
  "libxdamage1",
  "libxrandr2",
  "libxshmfence1",
  "xdg-utils"
]